### ISSUE TITLE
Incorrect encoding of Route.prefix field

### ISSUE THREAD

**Issue by yoursunny** [amar-ox/nms-console#5]
The [configuration schema](https://github.com/amar-ox/nms-microservice/blob/d92fc9be1738c98af7a2f9c15f2165f6e9441bf1/docs/openapi/controller-to-agent.yaml#L281-L283) specifies that `Route.prefix` should be TLV-VALUE of Name.
However, the controller and GUI are erroneously including TLV-TYPE and TLV-LENGTH of Name.
![screenshot](https://user-images.githubusercontent.com/1141273/94032948-7d719300-fd8e-11ea-9101-ca9f5f132f15.png)
```shell
~$ echo BwYIAWEIAWI= | base64 -d | hexdump -C
00000000  07 06 08 01 61 08 01 62                           |....a..b|
00000008
```

**Comment by Pesa** [comment]
I don't see any problems with including TLV type and length in the prefix if that's simpler to implement. Just update the schema.

**Comment by yoursunny** [comment]
As far as I know, the GUI uses NDNts `@ndn/packet` package to implement this feature.

It is *easier* to use TLV-VALUE:

* `name.value` property returns TLV-VALUE
* `Name` constructor accepts TLV-VALUE

You'll have the deal with `Encoder` and `Decoder` to use whole TLV.
